In [8]:
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import random 
from matplotlib import pyplot as io 

### Setting seed ###
random.seed(100)
np.random.seed(100)

# Image to array 

data_loc = "/Users/abhishekhosmani/CompSci/College/ML_Anjum/data/assignment5/"

img1 = io.imread(data_loc+"Koala.jpg")  #image is saved as rows * columns * 3 array  
print(img1[:3,:,:])

rows, cols, depth = img1.shape


[[[101  90  58]
  [103  92  62]
  [110  95  66]
  ...
  [ 96  96  70]
  [104 103  73]
  [ 92  91  60]]

 [[102  89  57]
  [108  94  65]
  [106  92  65]
  ...
  [ 96  96  68]
  [100 101  70]
  [ 89  90  58]]

 [[106  95  65]
  [107  93  66]
  [106  94  68]
  ...
  [ 96  96  68]
  [ 99 100  69]
  [ 95  96  65]]]


In [9]:
from matplotlib import pyplot as io
import numpy as np
from PIL import Image
from sklearn.cluster import KMeans

# Image to array 

data_loc = "/Users/abhishekhosmani/CompSci/College/ML_Anjum/data/assignment5/"

src_img = io.imread(data_loc+"Koala.jpg")  #image is saved as rows * columns * 3 array  
# print(src_img)

rows, cols, depth = src_img.shape

reshaped_img = src_img.reshape(rows*cols,depth)

kmeans = KMeans(n_clusters=5, max_iter=2)
kmeans.fit(reshaped_img)

output_img = kmeans.labels_.reshape(rows, cols)
io.imsave('compessed_sk_5.jpg', output_img)
print("COMPLETE")

COMPLETE


In [23]:
class KMeansCompression():
    def __init__(self, n_clusters=10):
        pasd
    
    def get_initial_centers(X, k):
        c = random.sample(list(X),K)
        return c
    
    def get_eucledian_distance(A, B):
        distance = np.sum()
    

In [71]:
data = np.array([[1,5,3], [2,1,4], [3,2,8], [1,1,1]])
result = []
n = len(a)

np.random.shuffle(data)
centers = data[:2]
print(centers)
for i in range(100):
    groups = {}
    
    for i in range(2):
        groups[i] = []
        
    for data_point in data:
        distances = [np.linalg.norm(data_point-centers[centroid]) for centroid in centers]
        print(distances)

[[3 2 8]
 [1 5 3]]


IndexError: index 3 is out of bounds for axis 0 with size 2

In [79]:
from matplotlib import pyplot as io
import numpy as np
from PIL import Image
from sklearn.cluster import KMeans

# Image to array 

data_loc = "/Users/abhishekhosmani/CompSci/College/ML_Anjum/data/assignment5/"

src_img = io.imread(data_loc+"Koala.jpg")  #image is saved as rows * columns * 3 array  
# print(src_img)

rows, cols, depth = src_img.shape

reshaped_img = src_img.reshape(rows*cols,depth)


def k_means_clustering(data, k, n_iter=300):
    # Create corresponding label array (Initialize with Label: -1)
    labels = np.full((data.shape[0],), -1)

    # Choose initial clusters by shuffling and choosing top k
    # np.random.shuffle(data)
    init_centers = data[:k]

    # Iteration Loop
    for i in range(n_iter):
            
        print('Iteration: ' + str(i + 1))
        groups = {}
        
        for i in range(k):
            groups[i] = []

        # Label them via closest point
        for color_index, rgb in enumerate(data):
            rgb_matrix = np.repeat(rgb, k).reshape(3, k).T
            
            # Find the Closest Label via L2 Norm
            closest_center = np.argmin(np.linalg.norm(rgb_matrix-init_centers, axis=1))
            print(closest_center)
            labels[color_index] = closest_center

            if (points_by_label[closest_center] is None):
                points_by_label[closest_center] = []

            points_by_label[closest_center].append(rgb)

        # Optimize Cluster Prototypes (Center of Mass of Cluster)
        for k_i in range(k):
            if (points_by_label[k_i] is not None):
                init_centers = np.asarray(points_by_label[k_i]).sum(axis=0) / len(points_by_label[k_i])
                init_centers[k_i] = new_cluster_prototype

        # Find Current Distortion Distances
        print_distortion_distance(init_centers, points_by_label, k)

    return (labels, init_centers)
k_means_clustering(data,2)

Iteration: 1


NameError: name 'new_cluster_prototype' is not defined

In [ ]:
for i in range(self.k):
    self.centroids[i] = np.array(random.sample(set(data),k))

for i in range(self.max_iter):
    self.groups = {}

    for i in range(self.k):
        self.groups[i] = []

    for data_point in data:
        distances = [np.linalg.norm(data_point-self.centroids[centroid]) for centroid in self.centroids]
        classification = distances.index(min(distances))
        self.classifications[classification].append(featureset)